source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'formtastic'
gem 'haml'
gem 'paperclip'
gem 'aws-s3'
gem 'rmagick'

group :development do
  gem 'nifty-generators'
  gem 'jquery-rails'
end

group :test do
  gem 'mocha'
  gem 'rspec-rails'
end
